// ctrl signs
`define reg_w_enable 1'b1
`define reg_w_disable 1'b0
`define mem_w_enable 1'b1
`define mem_w_disable 1'b0
`define jmp_enable 1'b1
`define jmp_disable 1'b0
`define default_jmp_addr 32'h0
`define zeroWord 32'h0
`define mem_r_disable 1'b0
`define mem_r_enable 1'b1
